[tool.isort]
profile = "black"
multi_line_output = 3
order_by_type = false

[tool.mypy]
disallow_incomplete_defs = true
disallow_untyped_defs = true
files = "."

[[tool.mypy.overrides]] # Overrides for currently untyped modules
module = [
    "docs.*",
    "docs.ext.*",
    "gitlab.v4.objects.epics",
    "gitlab.v4.objects.files",
    "gitlab.v4.objects.geo_nodes",
    "gitlab.v4.objects.issues",
    "gitlab.v4.objects.jobs",
    "gitlab.v4.objects.labels",
    "gitlab.v4.objects.merge_request_approvals",
    "gitlab.v4.objects.milestones",
    "gitlab.v4.objects.pipelines",
    "gitlab.v4.objects.repositories",
    "gitlab.v4.objects.services",
    "gitlab.v4.objects.sidekiq",
    "gitlab.v4.objects.snippets",
    "tests.functional.*",
    "tests.functional.api.*",
    "tests.unit.*",
    "tests.smoke.*"
]
ignore_errors = true

[tool.semantic_release]
branch = "main"
version_variable = "gitlab/__version__.py:__version__"
commit_subject = "chore: release v{version}"
commit_message = ""
